// JOB DSERV TOS DIRECTORY LISTING
* // ASSGN SYSRLB,X'187'  FOR PRIVATE RL
* // ASSGN SYSSLB,X'187'  FOR PRIVATE SL
// EXEC DSERV
 DSPLY CD,RD,SD
/*
/* DSPLY CD     DISPLAY CORE IMAGE DIRECTORY
/* DSPLY RD     DISPLAY RELOCATABLE DIRECTORY
/* DSPLY SD     DISPLAY SOURCE STATEMENT DIRECTORY
/&
