set console -n -q log=console.txt 
set debug -n -q debug.txt

; Motorola Exorciser with ExorDisk-I and line printer Emulation
; create a new Bootable EDOS-II System floppy for Motorola Exorciser

set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug

; use real Exorciser Memory Map

; Memory Map:
;	System has ram in 0000..FFFF
;       PROM for Resident EDOS-II: E800..EBFF
;       Disk Controller card PIAs: EC00..EC07
;       Printer in EC26..EC27
;       EXBUG Monitor: F000..FBFF 
;       Console I/O ACIAs in FCF4..FCF5
; 
set mp-b2 64k
set mp-b2 iobase=fcf0

; load in EXBUG 1.1 Exorciser Monitor 
; and disk controller PROM (EDOS Resident part)
; including code for Line Printer support

load exbug11.bin f000
load Build/PROM.S19
load Build/PROM_LPT.S19

; after loading ROM and PROM, identify the lowest ROM address 
; this address will be set as read-only. This is necessary to 
; cope with routines that destructively scan memory map to 
; detect end of RAM

set mp-b2 rombase=e800

; on Exorciser, area in FFF8..FFFF is RAM
; place RESET vector to start CPU

dep fffe f0
dep ffff 00

reset 

; enable M68SP702 702 Printer with MEX68PI Printer Interface I/O Module.
; set i/o address according to Motorola Exorciser Memoy Map

set lpt ExorPrinter
set lpt iobase=ec26

; enable ExorDisk-I (= iCOM FD360 OEMed) floppy controller 
; set i/o address according to Motorola Exorciser Memoy Map

set icom enabled
set icom iobase=ec00

; create a new blank system disk
att icom0 -n -q Work/Blank0.dsk
set icom0 rw

; create a blank disk and insert it in drive 1
att icom1 -q -n Work/Blank.dsk

; start symbolic trace
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all

; load source code for symbolic debugging
load EXBUG11.LST
load Build/PROM.LST
load Build/PROM_LPT.LST
load Build/EXEC_EDOS_2.6.LST

; boot Monitor 
go until "EXBUG"

; load EDOS-II Executive from paper tape
att ptr Build/EXEC_EDOS_2.6.S19

; load the EXEC main code (named EDOS 2.6 in S0 record)
send "LOAD"
go until "SGL/CONT"
send "S"
go until "EXBUG"

; start the executive
send "MAID"
go until "*"
send "E020;G"
go until "!"

; EDOS-II commands
;
; command                            ------------------Device-----------------------------------
;                                    Console    Printer   Cassette   TTY      Paper Tape Rdr/Pch
; disk directory to ...              CDIR       PDIR
; dumps file to ...                                       CDUMP      TDUMP
; list file to ...                   CLIST      PLIST
; loads to file from ...                                  CTAPE      TTAPE    PTAPE
; gen system: get exec from ...                           CXGEN      TXGEN    PXGEN
; 
; Cassette and TTY are mapped to Paper Tape Rdr/Pch

; place the executive again in paper tape reader, so it can be loaded to new system floppy
det ptr
att ptr Build/EXEC_EDOS_2.6.S19

; generate a system disk
; we use PXGEN as Executive program will be read from paper tape via TTY 
send "TXGEN"
send "\r"
go until "!"

; initialize work disk

send "INIT:1"
send "\r"
go until "!"

; load Astral-2000 ASSEMBLER from paper tape into work disk 

att ptr Build/ASMB.S19

send "TTAPE,ASMX:1"
send "\r"
go until "!"

det ptr

; load existing ASSEMBLER patch (Build/ASMP_EDOS.S19 file) from paper tape into 
; work disk (ASMPO file)

att ptr Build/ASMP_EDOS.S19

send "TTAPE,ASMPO:1"
send "\r"
go until "!"

det ptr

; then create a new ASSEMBLER prog using Astral 2000 Assembler plus patch

send "MERGE,ASMB,ASMX:1,ASMPO:1"
send "\r"
go until "!"

send "PURGE:1,ASMPO"
send "\r"
go until "!"

; load ASSEMBLER patch source (Source/ASMP_EDOS.ASM file) from paper tape into 
; work disk (ASMPS file)

att ptr Source/ASMP_EDOS.ASM

send "TTAPE,ASMPS:1"
send "\r"
go until "!"

det ptr

; assemble the patch, with printed listing 

att lpt -q -n Build/ASMP_EDOS.LST

send "ASM,2,ASMPO:1,ASMPS:1"
send "\r"

go until "PRINTER?"
send "Y"

go until "!"

det lpt

; punch new ASSEMBLER patch (Build/ASMP_EDOS.S19 file) to paper tape 
; from work disk (ASMPO file)

att ptp -q -n Build/ASMP_EDOS.S19

send "TDUMP,ASMPO:1"
send "\r"
go until "!"

det ptp

; load EDITOR from paper tape into work disk 
; It is an EDOS-II version, so no need to patch it

att ptr Build/EDIT.S19

send "TTAPE,EDIT"
send "\r"
go until "!"

det ptr

; load EDOS-II 2.6 EXECUTIVE source (Source/EXEC_EDOS_2.6.ASM file) from paper tape into 
; work disk (EXECS file)

att ptr Source/EXEC_EDOS_2.6.ASM

send "TTAPE,EXECS:1"
send "\r"
go until "!"

det ptr

; assemble, with printed listing 

att lpt -q -n Build/EXEC_EDOS_2.6.LST

send "ASM,2,EXECO:1,EXECS:1"
send "\r"
go until "PRINTER?"
send "Y"
go until "!"

det lpt

; punch (Build/EXEC_EDOS_2.6.S19 file) to paper tape 
; from work disk (EXECO file)

att ptp -q -n Build/EXEC_EDOS_2.6.S19

send "TDUMP,EXECO:1"
send "\r"
go until "!"

det ptp

; load Exordisk-I PROM source (Build/PROM.ASM file) from paper tape into 
; work disk (PROMS file)

att ptr Build/PROM.ASM

send "TTAPE,PROMS:1"
send "\r"
go until "!"

det ptr

; assemble, with printed listing 

att lpt -q -n Build/PROM.LST

send "ASM,2,PROMO:1,PROMS:1"
send "\r"
go until "PRINTER?"
send "Y"
go until "!"

det lpt

; punch (Build/PROM.S19 file) to paper tape 
; from work disk (PROMO file)

att ptp -q -n Build/PROM.S19

send "TDUMP,PROMO:1"
send "\r"
go until "!"

det ptp

; load PROM Patch source (Source/PROM_LPT.ASM file) from paper tape into 
; work disk (PROMS file)
; this patch allows Line Priner operation and fixes a bug on loading EDOS 2.7 

att ptr Source/PROM_LPT.ASM

send "TTAPE,PRLPS:1"
send "\r"
go until "!"

det ptr

; assemble, with printed listing 

att lpt -q -n Build/PROM_LPT.LST

send "ASM,2,PRLPO:1,PRLPS:1"
send "\r"
go until "PRINTER?"
send "Y"
go until "!"

det lpt

; punch (Build/PROM_LPT.S19 file) to paper tape 
; from work disk (PRLPO file)

att ptp -q -n Build/PROM_LPT.S19

send "TDUMP,PRLPO:1"
send "\r"
go until "!"

det ptp

; copy generated ASMB and EDIT to work disk

send "MERGE,ASMB:1,ASMB"
send "\r"
go until "!"
send "MERGE,EDIT:1,EDIT"
send "\r"
go until "!"

; remove disk 0, insert new system disk

det icom0
att icom0 -n -q EDOS-II_System.dsk

; place the executive again in paper tape reader, so it can be loaded to new system floppy

att ptr Build/EXEC_EDOS_2.6.S19

; generate a system disk
; we use PXGEN as Executive program will be read from paper tape via TTY 
send "TXGEN"
send "\r"
go until "!"

; copy assembler/editor to system disk

send "MERGE,ASMB,ASMB:1"
send "\r"
go until "!"
send "MERGE,EDIT,EDIT:1"
send "\r"
go until "!"

; now attach original fortran disk and copy it
det icom1
att icom1 -q  Original_Disk/fortran2.img
set icom1 ro

send "CDIR:1"
send "\r"
go until "!"

; copy fortran

send "MERGE,FORT,FORT:1"
send "\r"
go until "!"
send "MERGE,FORLB,FORLB:1"
send "\r"
go until "!"
send "MERGE,RLOAD,RLOAD:1"
send "\r"
go until "!"

det icom1

; detach the file and attach it again as read/only

det icom0
att icom0 -q EDOS-II_System.dsk
set icom0 ro
att icom1 -q Work/Blank.dsk
set icom1 rw

send "CDIR"
send "\r"
go until "!"

send "CDIR:1"
send "\r"
go until "!"

goto end


:end
