set console -n -q log=console.txt 
set debug -n -q debug.txt

; Motorola Exorciser with ExorDisk-I and line printer Emulation

set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug

set mp-b2 64k
set mp-b2 iobase=fcf0

load exbug11.bin f000
load Build/PROM.S19
load Build/PROM_LPT.S19

set mp-b2 rombase=e800

dep fffe f0
dep ffff 00
reset 

set lpt exorprinter
set lpt iobase=ec26

set icom enabled
set icom iobase=ec00

att icom0 EDOS-II_System.dsk
att icom1 -q -n Work/Blank.dsk

; start symbolic trace
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all

go until "EXBUG"
send "MAID"
go until "*"
send "E800;G"
go until "!"

send "INIT:1"
send "\r"
go until "!"

send "CDIR"
send "\r"
go until "!"

go

:end
