set console -n -q log=console.txt 
set debug -n -q debug.txt

; Motorola Exorciser with ExorDisk-I and line printer Emulation

set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug

set mp-b2 64k
set mp-b2 iobase=fcf0

load exbug11.bin f000
load Build/PROM.S19
load Build/PROM_LPT.S19

set mp-b2 rombase=e800

dep fffe f0
dep ffff 00
reset 

set lpt exorprinter
set lpt iobase=ec26

set icom enabled
set icom iobase=ec00

att icom0 EDOS-II_System.dsk
att icom1 -q -n Work/Blank.dsk

; start symbolic trace
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all

go until "EXBUG"
send "MAID"
go until "*"
send "E800;G"
go until "!"

send "INIT:1"
send "\r"
go until "!"

send "CDIR"
send "\r"
go until "!"

; call the editor on a new file "HOLAS" on unit 1
; it is a convention to terminate filename with S for source files
;                                               O for S19 object files
send "EDIT,,HOLAS:1"
send "\r"
go until "@"

; prompt for editor is @
; Insert new text in editor workspace

send "I"

send "        NAM     HOLA \r"
send "        OPT     O,NOM,NOP  \r"
send "* \r"
send "* PRINT HOLA IN CONSOLE \r"
send "* \r"
send "EDOS    EQU     $E800     EDOS PROM Boot EDOS \r"
send "* \r"
send "EXBUG   EQU     $F000     EXBUG Cold start \r"
send "XBEGEN  EQU     $F003     Prompt for address \r"
send "XCBCDH  EQU     $F006     Convert hex to binary \r"
send "XCHEXL  EQU     $F009     Convert upper half to ascii \r"
send "XCHEXR  EQU     $F00C     Convert lower half to ascii \r"
send "XINADD  EQU     $F00F     Get 4 hex digits from user \r"
send "XINCH   EQU     $F012     Input byte with echo \r"
send "XINCHN  EQU     $F015     Input char with echo (strip bit 7) \r"
send "XOUTCH  EQU     $F018     Output character \r"
send "XOUT2H  EQU     $F01B     Output byte in hex then space \r"
send "XOUT4H  EQU     $F01E     Output 2 bytes in hex then space \r"
send "XPCRLF  EQU     $F021     Print CR-LF \r"
send "XPDATA  EQU     $F024     Print CR-LF then string \r"
send "XPDAT1  EQU     $F027     Print string \r"
send "XPSPAC  EQU     $F02A     Print space \r"
send "* \r"
send "CR      EQU     $0D       CARRIAGE RETURN \r"
send "LF      EQU     $0A       LINE FEED \r"
send "EOF     EQU     $1A       END OF TEXT FILE \r"
send "* \r"
send "        ORG     $0100 \r"
send "* \r"
send "START   LDX     #MSG \r"
send "        JSR     XPDATA \r"
send "        JMP     EDOS \r"
send "* \r"
send "MSG     FCC     /Hola/ \r"
send "        FCB     CR,LF,4 \r"
send "* \r"
send "        END \r"
send "* \r"

; assembler does not likes blank lines. Add a "*" at begin of line
; not needed to terminate text with Control-Z (ascii 26, hex $1A) 
; automatically added by EDIT

; terminate insert command
send "\e\e"
go until "@"

; save to disk and return to EDOS
send "E"
send "\e\e"
go until "!"

; show unit 1 working disk contents
send "CDIR,1"
send "\r"
go until "!"

; show created file
send "CLIST,HOLAS:1"
send "\r"
go until "!"

send "ASM,2,HOLAO:1,HOLAS:1"
send "\r"
go until "PRINTER?"
send "N"
go until "\r\nTOTAL ERRORS "
go until "!"

; show unit 1 working disk contents
send "CDIR:1"
send "\r"
go until "!"

; list assembled prog
send "CLIST,HOLAO:1"
send "\r"
go until "!"

; load prog and go to monitor
send "LOAD,HOLAO:1"
send "\r"
go until "EXBUG"

send "MAID"
go until "*"
send "0100;G"
go until "!"

; demo fortran compiler

; load FORTRAN Sample program (Source/SORT_Fortran_Sample.FTN file) from paper tape into 
; work disk (SORTF file)

att ptr Source/SORT_Fortran_Sample.FTN

send "TTAPE,SORTF:1"
send "\r"
go until "!"

det ptr

; list assembled prog
send "CLIST,SORTF:1"
send "\r"
go until "!"

; compile to generate a relocatable object file (SORTR)

send "FORT,,SORTR:1,SORTF:1"
send "\r"
go until "!"

; link 

send "RLOAD"
send "\r"
go until "?"

send "IDON"
send "\r"
go until "?"

; use compiled relocatable object file 
send "LOAD=SORTR:1"
send "\r"
go until "?"

; use fortran library
send "LOAD=FORLB"
send "\r"
go until "?"

; set absolute binary prog to generate
send "BO=SORT:1"
send "\r"
go until "?"
send "ABSP"
send "\r"
go until "?"

; load relocatables again for second pass
send "LOAD=SORTR:1"
send "\r"
go until "?"
send "LOAD=FORLB"
send "\r"
go until "?"

;show link map
send "MAPF"
send "\r"
go until "?"

;return to EDOS
send "EXIT"
send "\r"
go until "!"

; show unit 1 working disk contents
send "CDIR:1"
send "\r"
go until "!"

; load prog and go to monitor
send "LOAD,SORT:1"
send "\r"
go until "EXBUG"

send "MAID"
go until "*"
send "0020;G"

go until "ENTER TEN INTERGERS AT ?"
go until "?"
send "17,13,66,88,43,56,18,97,103,44"
send "\r"
go until "ENTER TEN INTERGERS AT ?"
go until "?"
send "0"
send "\r"

go until "!"

go

:end
