set console -n -q log=Source/build_console.txt 
set debug -n -q debug.txt

; Motorola Exorciser with ExorDisk-I 
; create a new Bootable EDOS-I System floppy for Motorola Exorciser

set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug

; use real Exorciser Memory Map

; Memory Map:
;	System has ram in 0000..FFFF
;       PROM for Resident EDOS-I: E800..EBFF
;       Disk Controller card PIAs: EC00..EC07
;       EXBUG Monitor: F000..FBFF 
;       Console I/O ACIAs in FCF4..FCF5
; 
set mp-b2 64k
set mp-b2 iobase=fcf0

; load in EXBUG 1.1 Exorciser Monitor 
; and disk controller PROM (EDOS Resident part)

load exbug11.bin f000
load Build/PROM.S19

; after loading ROM and PROM, identify the lowest ROM address 
; this address will be set as read-only. This is necessary to 
; cope with routines that destructively scan memory map to 
; detect end of RAM

set mp-b2 rombase=e800

; on Exorciser, area in FFF8..FFFF is RAM
; place RESET vector to start CPU

dep fffe f0
dep ffff 00

reset 

; enable ExorDisk-I (= iCOM FD360 OEMed) floppy controller 
; set i/o address according to Motorola Exorciser Memoy Map

set icom enabled
set icom iobase=ec00

; create a new system disk
att icom0 -n -q EDOS-I_System.dsk

; create a blank disk and insert it in drive 1
att icom1 -q -n Work/Blank.dsk

; start symbolic trace
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all

; load source code for symbolic debugging
load EXBUG11.LST
load Build/PROM.LST
load Build/EXEC_EDOS_1.LST

; boot Monitor 
go until "EXBUG"

; load EDOS-I Executive from paper tape
att ptr Build/EXEC_EDOS_1.S19

; load the EXEC main code
send "LOAD"
go until "SGL/CONT"
send "S"
go until "EXBUG"
det ptr

; load EDOS-I Executive I/O Patch from paper tape
att ptr Build/EXECP.S19

; load the EXEC main code
send "LOAD"
go until "SGL/CONT"
send "S"
go until "EXBUG"
det ptr

; set paper tape punch to no echo to SimH console punched chars
set ptp noecho 

; punch patched Executive to be loaded later on disk
att ptp -q -n Work/EXEC.S19

; punch range 0020-08BF
send "PNCH"
go until "BEG ADDR"
send "0020"
send "\r"
go until "END ADDR"
send "08BF"
send "\r"
go until "HDR"
send "EXEC  "
go until "EXEC"
send "Y"
go until "BEG ADDR"
send "X"
go until "EXBUG"

det ptp

; start the executive
send "MAID"
go until "*"
send "0020;G"
go until "!"

; EDOS-I commands
;
; command                            ------------------Device-----------------------------------
;                                    Console    Printer   Cassette   TTY      Paper Tape Rdr/Pch
; disk directory to ...              L
; dumps file to ...                                       DC         DT
; list file to ...                              P
; loads to file from ...                                  SC         ST       SP
; gen system: get exec from ...                           XC         XT       XP
; 
; DT -> will show the file in console
; DC -> will send the file to Paper tape Punch PTP device
; ST -> will read the file from Paper tape Reader PTR device 

; Printer is mapped to console 

; initialize work disk in drive 1
send "I1"
send "\r"
go until "!"

; Load Assembler base to disk 1 as file 1
att ptr Build/ASMB10_BASE.S19
send "ST11"
send "\r"
go until "!"
det ptr

; Load Assembler EDOS patch to disk 1 as file 2
att ptr Build/ASMB10_EDOS.S19
send "ST12"
send "\r"
go until "!"
det ptr

; append contents of file 2 at end of file 1
; i.e. append ASMB10_EDOS.S19 to ASMB10_BASE.S19
send "T12,11"
send "\r"
go until "!"

; punch resulting file: is the patched assembler ready to be used
att ptp -q -n Work/ASMB10.S19
send "DC11"
send "\r"
go until "!"
det ptp

; Load Editor base to disk 1 as file 3
att ptr Build/EDIT10.S19
send "ST13"
send "\r"
go until "!"
det ptr

; Load Assembler EDOS patch to disk 1 as file 4
att ptr Build/EDTP10.S19
send "ST14"
send "\r"
go until "!"
det ptr

; append contents of file 4 at end of file 3
; i.e. append EDTP10.S19 to EDIT10.S19
send "T14,13"
send "\r"
go until "!"

; punch resulting file: is the patched assembler ready to be used
att ptp -q -n Work/EDIT10.S19
send "DC13"
send "\r"
go until "!"
det ptp

; list unit 1
send "L1"
send "\r"
go until "!"

; generate system disk:

; 1) Store Executive, read from paper tape via TTY 
att ptr Work/EXEC.S19
send "XT0"
send "\r"
go until "!"
det ptr

; 2) Store Editor, read from paper tape via TTY 
att ptr Work/EDIT10.S19
send "XT1"
send "\r"
go until "!"
det ptr

; 3) Store Assembler, read from paper tape via TTY 
att ptr Work/ASMB10.S19
send "XT2"
send "\r"
go until "!"
det ptr

; Load EXEC patch source to work disk as file 1 
; note: assembler 1.0 requires text file with <CR><LF> line end
; any other line ending generates a 205/207 assembler error
att ptr Source/EXECP.ASM
send "ST11"
send "\r"
go until "!"
det ptr
; name the file in dir
send "N11,EXECP.ASM"
send "\r"
go until "!"

; Load ASMB EDOS patch source to work disk as file 3
att ptr Source/ASMB10_EDOS.ASM
send "ST13"
send "\r"
go until "!"
det ptr
; name the file in dir
send "N13,ASMBP.ASM"
send "\r"
go until "!"

; Load EDIT patch source to work disk as file 5
att ptr Source/EDTP10.ASM
send "ST15"
send "\r"
go until "!"
det ptr
; name the file in dir
send "N15,EDITP.ASM"
send "\r"
go until "!"

; assemble EXEC patch
send "A11,12,2"
send "\r"
go until "!"
send "N12,EXECP.S19"
send "\r"
go until "!"

; assemble ASMB EDOS patch
send "A13,14,2"
send "\r"
go until "!"
send "N14,ASMBP.S19"
send "\r"
go until "!"

; assemble EDIT patch
send "A15,16,2"
send "\r"
go until "!"
send "N16,EDITP.S19"
send "\r"
go until "!"

; list work disk dir
send "L1"
send "\r"
go until "!"

; punch s19 files is the patched assembler ready to be used
att ptp -q -n Build/EXECP.S19
send "DC12"
send "\r"
go until "!"
det ptp
att ptp -q -n Build/ASMB10_EDOS.S19
send "DC14"
send "\r"
go until "!"
det ptp
att ptp -q -n Build/EDTP10.S19
send "DC16"
send "\r"
go until "!"
det ptp

; Load Assembler demo to disk as file 3
att ptr Source/ASM_Sample.ASM
send "ST3"
send "\r"
go until "!"
det ptr

; name file 3 as "HOLA.ASM"
send "N3,HOLA.ASM"
send "\r"
go until "!"

; list dir
send "L"
send "\r"
go until "!"

; Load file 3 (source file) in editor
send "E3,4"
send "\r"
go until "@"

; use A command (append) to load 50 lines of source file in text buffer
; (commands are terminated with <ESC><ESC>)
send "A"
send "\x1B\x1B"

; uncomment to generate symbolic debug trace for EDIT execution
; load Build/EDIT10.LST
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all
; go until "@"
; goto end

go until "@"
; use B command (begin) to place the edit pointer on top of file
send "B"
send "\x1B\x1B"
go until "@"
; use T command (type) to type the given n lines starting at edit pointer
send "10T"
send "\x1B\x1B"
go until "@"
; use E command (end) to save the whole file in output file and return
send "E"
send "\x1B\x1B"
go until "!"

; assemble source file 3, generate object file 4
send "A3,4,2"
send "\r"

; uncomment to generate symbolic debug trace for ASMB execution
; load Build/ASMB10_BASE.LST
; load Build/ASMB10_EDOS.LST
; go until 0400
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all
; go until "!"
; goto end

go until "!"

; name file 4 as "HOLA.S19"
send "N4,HOLA.S19"
send "\r"
go until "!"

; list dir
send "L"
send "\r"
go until "!"

; List file 4 in console (object file)
send "DT4"
send "\r"
go until "!"

; Run file 4 (object file). Prog start at $0100
send "R4"
send "\r"
go until "EXBUG"
send "MAID"
go until "*"
send "0100;G"
go until "!"

goto end


:end
