set console -n -q log=Source/build_console.txt 
set debug -n -q debug.txt

; create a new Bootable FDOS-II System floppy 

set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug

; Memory Map:
;	System has ram in 0000..FFFF
;       Console I/O ACIAs in 8000..8007 
;       PR40 printer in 801C..801D
;       Monitor: E800..EFFF and FFF8..FFFF
;       PROM for Resident FDOS-II: F000..F3FF
;       Disk Controller card PIAs: F800..F807
; 
set mp-b2 64k
set mp-b2 iobase=8000

; as system has no rom, Monitor loads in ram (SWTPC based)
; disk controller PROM (FDOS Resident part) loads in ram

load Build/SMON.S19
load Build/FDOSRES.S19

; should reset after loading the monitor, so cpu read the
; just loaded RESET vector at $FFFE
reset 

; enable printer
set lpt pr40
set lpt iobase=801c

; enable iCOM FD360 floppy controller 
; set i/o address according to ASTRAL 2000 Memoy Map

set icom enabled
set icom iobase=f800

; create a new blank system disk
att icom0 -q -n FDOS-II_System.dsk
set icom0 rw

; create a blank disk and insert it in drive 1
att icom1 -q -n Work/Blank.dsk

; start symbolic trace
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all

; load source code for symbolic debugging
load Build/SMON.LST
load Build/FDOSRES.LST
load Build/EXEC.LST

; boot Monitor 
go until "$"

; load FDOS-II Executive from paper tape
att ptr Build/EXEC.S19

; load the jump vectors at begging of EXEC
send "L"
go until "$"
; load the EXEC main code (named EXECB in S0 record)
send "L"
go until "$"

; start the executive
send "J0100"
go until "!"

; place the executive again in paper tape reader, so it can be loaded to new system floopy
det ptr
att ptr Build/EXEC.S19

; send XGEN command to generate a system disk
send "XGEN"
send "\r"
go until "!"

; now load editor and assembler to system disk
det ptr
att ptr Build/EDIT.S19

send "LOAD,EDIT"
send "\r"
go until "!"

det ptr
att ptr Build/ASMB.S19

send "LOAD,ASMB"
send "\r"
go until "!"

det ptr

send "LIST"
send "\r"
go until "!"

; make both permament files (so cannot be deleted)

send "CHGAT,EDIT,1"
send "\r"
go until "!"

send "CHGAT,ASMB,1"
send "\r"
go until "!"

; load utilities: iCOM disk Drive diagnostics (DIAGO) and copy mem to file (FDSKO)
att ptr Build/DIAGO.S19

send "LOAD,DIAGO"
send "\r"
go until "!"

det ptr
att ptr Build/FDSKO.S19

send "LOAD,FDSKO"
send "\r"
go until "!"

det ptr

send "LIST"
send "\r"
go until "!"

; initialize work disk

send "INIT,1"
send "\r"
go until "!"

; load into work disk ASM patch to allow 
; assembly listing to be sent to line printer

att ptr Source/ASMPATCH.ASM

send "LOAD,APAT:1"
send "\r"
go until "!"

det ptr

; assemble the patch 

send "ASMB,APAT:1,APATO:1,2"
send "\r"
go until "\r\nTOTAL ERRORS "
go until "!"

; rename system assembler as ASMBX

send "RENAM,ASMB,ASMBX"
send "\r"
go until "!"

; then create a new ASMB prog using renamed system assembler contatenated with patch

send "MERGE,ASMB,ASMBX,APATO:1"
send "\r"
go until "!"

send "DELET:1,APATO"
send "\r"
go until "!"

send "LIST"
send "\r"
go until "!"

; assemble patch with new created ASMB to get the printed listing

att lpt -q -n Build/ASMPATCH.LST

send "ASMB,APAT:1,APATO:1,2"
send "\r"
go until "PRINTER?"
send "Y"
go until "\r\nTOTAL ERRORS "
go until "!"

det -q lpt

; load into work disk BASIC patch to fix
; LOAD/SAVE and TLOAD/TSAVE commands

att ptr Source/BASPATCH.ASM

send "LOAD,BPAT:1"
send "\r"
go until "!"

det ptr

; assemble basic patch and get the printed listing

att lpt -q -n Build/BASPATCH.LST

send "ASMB,BPAT:1,BPATO:1,2"
send "\r"
go until "PRINTER?"
send "Y"
go until "\r\nTOTAL ERRORS "
go until "!"

det -q lpt

; now load unpatched BASIC in work disk, append the patch to
; create a BASIC patched version on system disk

att ptr Build/BASIC.S19

send "LOAD,BAS:1"
send "\r"
go until "!"

det ptr

send "MERGE,BASIC,BAS:1,BPATO:1"
send "\r"
go until "!"

send "LIST"
send "\r"
go until "!"

send "LIST,1"
send "\r"
go until "!"

; now assemble the original Astral 2000 Monitor 
; to generate the listing file for reference
; this monitor is not used in SimH (intead SMON is used)

att ptr Build/ASTMON.ASM

send "LOAD,MON2S:1"
send "\r"
go until "!"

det ptr

att lpt -q -n Build/ASTMON.LST

send "ASMB,MON2S:1,MON2O:1,2"
send "\r"
go until "PRINTER?"
send "Y"
go until "\r\nTOTAL ERRORS "
go until "!"

det -q lpt


; now assemble the original iCOM diagnostric program 
; to generate the listing file for reference

att ptr Build/DIAGS.ASM

send "LOAD,DIAGS:1"
send "\r"
go until "!"

det ptr

att lpt -q -n Build/DIAGS.LST

send "ASMB,DIAGS:1,DIAGO:1,2"
send "\r"
go until "PRINTER?"
send "Y"
go until "\r\nTOTAL ERRORS "
go until "!"

det -q lpt


; now assemble the iCOM drive PROM (that holds the resident 
; part of FDOS operating system). Dump the resulting object
; file to be used by SimH

att ptr Build/FDOSRES.ASM

send "LOAD,RES2S:1"
send "\r"
go until "!"

det ptr

att lpt -q -n Build/FDOSRES.LST

send "ASMB,RES2S:1,RES2O:1,2"
send "\r"
go until "PRINTER?"
send "Y"
go until "\r\nTOTAL ERRORS "
go until "!"

det -q lpt

att ptp -q -n Build/FDOSRES.S19

send "DUMP,RES2O:1"
send "\r"
go until "!"

det ptp

; now assemble the ROM Monitor that replaces SWTBUG for SimH emulator 
; with routines expected by PROM 

att ptr Source/SMON.ASM

send "LOAD,SMONS:1"
send "\r"
go until "!"

det ptr

att lpt -q -n Build/SMON.LST

send "ASMB,SMONS:1,SMONO:1,2"
send "\r"
go until "PRINTER?"
send "Y"
go until "\r\nTOTAL ERRORS "
go until "!"

det -q lpt

att ptp -q -n Build/SMON.S19

send "DUMP,SMONO:1"
send "\r"
go until "!"

det ptp

; delete ASMB with PRINT? feature, restore original ASMB
; then load FDOS executive as file (so it can be used by XGEN command)

send "DELET,ASMB"
send "\r"
go until "!"

send "RENAM,ASMBX,ASMB"
send "\r"
go until "!"

att ptr Build/EXEC.S19

send "LOAD,EXEC"
send "\r"
go until "!"

det ptr

; detach the file and attach it again as read/only

det icom0
att icom0 -q FDOS-II_System.dsk
set icom0 ro

send "LIST"
send "\r"
go until "!"

send "LIST,1"
send "\r"
go until "!"

:end