set console -n -q log=console.txt 
set debug -n -q debug.txt

set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug

set mp-b2 64k
set mp-b2 iobase=8000

load Build/SMON.S19
load Build/FDOSRES.S19
reset 

set icom enabled
set icom iobase=f800

att icom0 FDOS-II_System.dsk
att icom1 -q -n Work/Blank.dsk

; start symbolic trace
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all

go until "$"
send "JF000"

go until "!"

send "INIT,1"
send "\r"
go until "!"

send "LIST"
send "\r"
go until "!"

go

:end
