set console -n -q log=console.txt 
set debug -n -q debug.txt

set cpu hex
set cpu itrap
set cpu nomtrap
set cpu nodebug

set mp-b2 64k
set mp-b2 iobase=8000

load Build/SMON.S19
load Build/FDOSRES.S19
reset 

set icom enabled
set icom iobase=f800

att icom0 FDOS-II_System.dsk
set icom0 ro
att icom1 -q -n Work/Blank.dsk

; start symbolic trace
; set cpu  debug=symb;inst
; set icom debug=all
; set mp-s debug=all

; load source code for symbolic debugging
load Build/SMON.LST
load Build/FDOSRES.LST
load Build/EXEC.LST

; boot Monitor 
go until "$"

; call Monitor entry point to boot FDOS from disk
send "JF000"
go until "!"

; show directory for unit 0 (system disk)
send "LIST"
send "\r"
go until "!"

; clear disk for unit 1 (will be our working disk)
send "INIT,1"
send "\r"
go until "!"

; call the editor on a new file "HOLAS" on unit 1
; it is a convention to terminate filename with S for source files
;                                               O for S19 object files

send "BUILD,HOLAS:1"
send "\r"
go until "@"

; prompt for editor is @
; Insert new text in editor workspace

send "I"

send "        NAM     HOLA \r"
send "        OPT     O,NOM,NOP  \r"
send "* \r"
send "* PRINT HOLA IN CONSOLE \r"
send "* \r"
send "FDOS    EQU     $F000     Boot FDOS \r"
send "UPDT    EQU     $F003     FDOS call updt \r"
send "* \r"
send "CI      EQU     $F006     CI    console char in  \r"
send "CO      EQU     $F009     CO    console char out \r"
send "RDI     EQU     $F00C     RDI   paper tape reader in \r"
send "LO      EQU     $F00F     LO    list output \r"
send "PO      EQU     $F012     PO    punch output \r"
send "EXIT    EQU     $F015     MONITOR \r"
send "* \r"
send "CR      EQU     $0D       CARRIAGE RETURN \r"
send "LF      EQU     $0A       LINE FEED \r"
send "EOF     EQU     $1A       END OF TEXT FILE \r"
send "* \r"
send "        ORG     $0100 \r"
send "* \r"
send "START   LDX     #MSG \r"
send "        JSR     PRTSTR \r"
send "        JMP     FDOS \r"
send "* \r"
send "MSG     FCB     CR,LF \r"
send "        FCC     /Hola/ \r"
send "        FCB     CR,LF,0 \r"
send "* \r"
send "PRTSTR  LDAA    $0000,X   Print StringZ at addr in reg X \r"
send "        BEQ     PRTEND \r"
send "        JSR     CO \r"
send "        INX  \r"
send "        BRA     PRTSTR \r"
send "PRTEND  RTS  \r"    
send "* \r"
send "        ORG     $E0FE    This is the prog start addr \r"
send "        FDB     START    used by RUNGO command \r"
send "* \r"
send "        END \r"
send "* \r"

; assembler does not likes blank lines. Add a "*" at begin of line
; not needed to terminate text with Control-Z (ascii 26, hex $1A) 
; automatically added by EDIT

; terminate insert command
send "\e\e"
go until "@"

; save to disk and return to FDOS
send "E"
send "\e\e"
go until "!"

; show unit 1 working disk contents
send "LIST,1"
send "\r"
go until "!"

; show created file
send "PRINT,HOLAS:1"
send "\r"
go until "!"

send "ASMB,HOLAS:1,HOLAO:1,2"
send "\r"
go until "\r\nTOTAL ERRORS "
go until "!"

; show unit 1 working disk contents
send "LIST,1"
send "\r"
go until "!"

; print assembled prog
send "PRINT,HOLAO:1"
send "\r"
go until "!"

; load prog and go to monitor
send "RUN,HOLAO:1"
send "\r"
go until "$"

send "J0100"
send "\r"
go until "!"

; run the prog as command
send "RUNGO,HOLAO:1"
send "\r"
go until "!"

; attach paper tape host file. No paper tape in reader makes LOAD command
; wait for tape forever. Just type ^Z (Control-Z) in console to 
; terminate the load

; paper tape files should be text files, terminated by ^Z
; if not ^Z at end of file, LOAD command will wait for forever
; Just type ^Z in console to terminate the load

att ptr Source/ASM_Sample.ASM

; load the monitor source code from paper tape
; into a FDOS file

send "LOAD,SMPLS:1"
send "\r"
go until "!"

; detach (remove) paper tape form paper tape file
det ptr

; show directory for unit 1 (work disk)
send "LIST,1"
send "\r"
go until "!"

send "PRINT,SMPLS:1"
send "\r"
go until "!"

send "ASMB,SMPLS:1,SMPLO:1,2"
send "\r"
go until "\r\nTOTAL ERRORS "
go until "!"

send "PRINT,SMPLO:1"
send "\r"
go until "!"

send "LIST,1"
send "\r"
go until "!"

; Attach a new paper tape host file
att ptp -q -n Work/ASM_Sample.S19

; dump the FDOS file to the paper tape punch 
; i.e.punch it in host file

send "DUMP,SMPLO:1"
send "\r"
go until "!"

; detach punched file
det ptp

; and attach it back into the reader
att ptr Work/ASM_Sample.S19

; load from paper tape into FDOS file
send "LOAD,SMP2O:1"
send "\r"
go until "!"

; print it
send "PRINT,SMP2O:1"
send "\r"
go until "!"

send "LIST,1"
send "\r"
go until "!"

; and run it
send "RUNGO,SMP2O:1"
send "\r"
go until "!"

;     set cpu  debug=symb;inst
;     set icom debug=all
;     set mp-s debug=all
;     load Build/basic.lst

send "RUNGO,BASIC"
send "\r"
go until ":"

send "FDOS"
send "\r"
go until "!"

; test loading a basic prog from paper tape

send "RUNGO,BASIC"
send "\r"
go until ":"

att ptr -q Source/BAS_Sample.txt

send 'TLOAD'
send "\r"

; the end of prog is marked in file read by char ^D (not ^Z !!!) 
; if missing, TLOAD hangs, but control can be regained by typing ^D in console
go until "END"
go until "\n"
send "\x04"
go until ":"

send 'LIST '
send "\r"
go until ":"

send 'RUN'
send "\r"
go until ":"

; test punching a basic prog on paper tape

att ptp -n -q Work/hola_bas.txt

send 'TSAVE'
send "\r"
go until ":"

det ptp

send 'NEW'
send "\r"
go until ":"

send 'LIST '
send "\r"
go until ":"

; test reading the punched paper tape back in tape reader

att ptr -q Work/hola_bas.txt

send 'TLOAD'
send "\r"

; the end of prog is marked in file read by char ^D (not ^Z !!!) 
; if missing, TLOAD hangs, but control can be regained by typing ^D in console
go until "END"
go until "\n"
send "\x04"
go until ":"

det ptr

send 'LIST '
send "\r"
go until ":"

send 'RUN '
send "\r"
go until ":"

; test saving to disk 

send 'CAT 1 '
send "\r"
go until ":"

send 'SAVE HOLA:1 '
send "\r"
go until "READY"
go until ":"

send 'CAT 1 '
send "\r"
go until ":"

send 'FDOS'
send "\r"
go until "!"

send "LIST,1"
send "\r"
go until "!"

send "PRINT,HOLA:1"
send "\r"
go until "!"

send "RUNGO,BASIC"
send "\r"
go until ":"

; test loading from disk 

send 'LOAD HOLA:1 '
send "\r"

go until "READY"
go until ":"

send 'LIST '
send "\r"
go until ":"

send 'RUN '
send "\r"
go until ":"

; test enter to monitor

send 'PATCH'
send "\r"
go until "$"

; show CPU registers

send 'R'
go until "$"

; return to basic

send 'G'
go until ":"

; back to operating system
send "FDOS"
send "\r"
go until "!"

send 'LIST'
send "\r"
go until "!"

go

:end
