set console -n -q log=console.txt 
set debug -n -q debug.txt

set bootrom 2708
attach bootrom swtbug.bin
set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug
set mp-b2 bd0, bd1, bd2, bd3, bd4, bd5

reset

; set cpu  debug=symb;inst
; set mp-s debug=all
; set ac30 debug=all

; set output to use onle plain bit 7 ascii
set mp-s 7bits

go until "$"

att ptr G2_MSBASIC_6800.s19
send "L"
go until "$"


; path to use the ac30 cassete port on CLOAD and CSAVE
; 1D09   FF 13 EB  STX     $13EB --> TST xxx (do not change addr of CASIN routine)
; 1D12   FF 13 33  STX     $1333 --> TST xxx (do not change addr of CASOUT routine)
dep 1d09 7d
dep 1d12 7d

; write byte to ac30 cassette port
; 14ac   F6 80 00  LDAB    $8000  --> read from AC30 status port
; 14af   C4 02     ANDB    #$02
; 14b1   27 F9     BEQ     $14ac
; 14b3   B7 80 01  STAA    $8001  --> write to AC30 data port
; 14b6   39        RTS     
dep 14ac   F6
dep 14ad   80
dep 14ae   00
dep 14af   C4
dep 14b0   02
dep 14b1   27
dep 14b2   f9
dep 14b3   B7
dep 14b4   80
dep 14b5   01
dep 14b6   39        

; 1482   B6 80 00  LDAA    $8000  --> read from AC30 status port
; 1485   46        RORA    
; 1486   24 FA     BCC     $1482
; 1488   B6 80 01  LDAA    $8001  --> read from AC30 data port
; 148b   39        RTS     
dep 1482   B6
dep 1483   80
dep 1484   00
dep 1485   46
dep 1486   24
dep 1487   fa
dep 1488   B6 
dep 1489   80
dep 148a   01
dep 148b   39


send "J0000"

go until "?"
send "\r"
go until "?"
send "\r"
go until "?"
send "Y\r"

; turn on the AC30 cassete interface
set ac30 on
; insert a new tape (file g2cassete.tap)
attach ac30 -n -q g2cassete.tap

go until "OK"
go until "\n"

send '10 PRINT "HOLA"'
send "\r"
send '20 END'
send "\r"

send 'LIST'
send "\r"

go until "OK"
go until "\n"

; before saving to tape, must press record key
set ac30 record

; then issue the basic command CSAVE
send 'CSAVE"P"'
send "\r"

go until "OK"
go until "\n"

; after saving to tape, must press stop key
set ac30 stop

send 'NEW'
send "\r"

go until "OK"
go until "\n"

send 'LIST'
send "\r"

go until "OK"
go until "\n"

; now, rewind tape ...
set ac30 rew
; ... then press play to load program just saved
set ac30 play

; and then issue the basic command CLOAD
send 'CLOAD"P"'
send "\r"

go until "OK"
go until "\n"

; after loading program, stop the tape
set ac30 stop

send 'LIST'
send "\r"

go until "OK"
go until "\n"

send 'RUN'
send "\r"

go until "OK"
go until "\n"

go

:end

