;*	NAM FLITB
	ORG $6200
;* SUBROUTINE "RELPOR" DETERMINES IF THE RELATIVE POSITION
;* OF THE AIRCRAFT HAS CHANGET WHILE THE PROGRAM HAS BEEN 
;* CALCULATING THE LAST TRASFTORMATIONS. IT DOES THIS BY
;* COMPARING THE NEWLY UPDATED VALUES RECEIVED BY THE A/D
;* NOW STORED IN LOCATIONS X3, Y3, Z3, PITCH, BANK, AND
;* ROLL TO THOSE VALUES WHICH WHERE PREVIOUSLY STORED IN
;* LOCATIONS M1, N1, N2, N3, N4 AND N5. IF ANY ONE OF THE
;* COMPARISIONS ARE NOT EQUAL THEN THE PLANE HAS CHANGED
;* IT'S RELATIVE POSITION AND THE PROGRAM WILL JUMP TO 
;* THE TRANSFORMATION ROUTINES AGAIN. IF THE COMPARISION
;* PROVES TO BE THE SAME THEN THE PROGRAM JUMPS BACK TO
;* THE ROUTINE "UPDATE" TO TRY TO CHANGE IN THE PARAMETERS.
;* IF THE ROUTINE DOES NOT GET A CHANGE IN THE PARAMETER
;* AFTER 5 TRIES IT WILL JUMP TO A ROUTINE WHICH WILL END
;* THE PROGRAM AFTER A "LANDED" MESSAGE IS PRINTED OUT TO
;* THE USER'S TERMINAL.
RELPOS  CLRA
EVAL 	LDAA X3
	CMPA M1
	BNE GOTRAN
	LDAA Y3
	CMPA N1
	BNE GOTRAN
	LDAA Z3
	CMPA N2
	BNE GOTRAN
	LDAA PITCH
	CMPA N3
	BNE GOTRAN
	LDAA BANK
	CMPA N4
	BNE GOTRAN
	LDAA HEAD
	CMPA N5
	BNE GOTRAN
MAKEQ   LDAA X3
	STAA M1
	LDAA Y3
	STAA N1
	LDAA Z3
	STAA N2
	LDAA PITCH
	STAA N3
	LDAA BANK
	STAA N4
	LDAA HEAD
	STAA N5
	LDAA FLGDUN
	INCA
	CMPA #4		;FLGDUN = 4 MAKES 4 TRIES THRU LOOP
	BEQ LANDED	;IF 5TH TRY PRINT LANDED MESSAGE AND QUIT
	JMP GOAGN	;NOT 5TH TRY GO TO MACRO ADN TRY FOR UPDATE
LANDED	JSR PRINTL	;LANDED SO GO PRINT MESSAGE
	SWI		;AND QUIT
PRINTL	LDX #MSGL	;INDEX REGUSTER <= START OF MESSAGE
	JMP DSPCHR	;ROUTINE "DSPCHR" HAS RTS FOR PRINTL
GOTRAN	RTS		;DATA IS DIFFERENT, GO CNVRT AND TRANSFORM
CNT	EQU $78F3		
XV	EQU $0100
YV	EQU $0102
ZV	EQU $0104
PV 	EQU $0106
BV 	EQU $0108
HV 	EQU $010A
X3	EQU $7800
Y3	EQU $7802
Z3	EQU $7804
PITCH	EQU $7806
BANK	EQU $7808
HEAD	EQU $780A
M1	EQU $780C
N1	EQU $780E
N2	EQU $7810
N3	EQU $7812
N4	EQU $7814
N5	EQU $7818
FLGDUN	EQU $781C
MSGL	EQU $7700
GOAGN	EQU $6016
DSPCHR	EQU $609F
	END
