* $$ JOB JNM=LVTOC,USER='OPER',CLASS=0,DISP=D
* $$ LST LST=00E,FNO=0001,CLASS=A,DISP=D
// JOB     LVTOC       - VOLUME VTOC DISPLAY UTILITY
*
* $$ NOTE              - RESPOND "YES" OR "NO" TO MSG 8V96D
*
// ASSGN   SYS004,X'131'
// ASSGN   SYS005,X'00E'
// EXEC    PGM=LVTOC
/*
/&
* $$ EOJ
