* $$ JOB JNM=STARTBG,USER='OPER',PRI=9,CLASS=0,DISP=D
* $$ LST LST=00E,FNO=0001,CLASS=A,DISP=D
   ASSGN   SYSLST,X'00E'
   ASSGN   SYSPCH,X'00D'
   ASSGN   SYSLNK,SYSRES
// JOB     STARTBG     - INITIALIZE BG DEVELOPMENT PARTITION
// OPTION PARSTD
/*
/&
* $$ EOJ
* $$ JOB JNM=STARTF2,USER='OPER',PRI=9,CLASS=2,DISP=D
* $$ LST LST=00E,FNO=0001,CLASS=A,DISP=D
   ASSGN   SYSLST,X'00E'
   ASSGN   SYSPCH,X'00D'
// JOB     STARTF2     - INITIALIZE F2 COMMUNICATIONS PARTITION
// OPTION PARSTD
/*
/&
* $$ EOJ
