ASSGN SYSLST,X'00E'
// JOB POWER04   POWER LOAD F1 PARSTD
// PAUSE MUST RUN IN F1
/* LOAD F1 PARTITION STANDARD LABEL FOR SYSIN FILE
// OPTION PARSTD
// DLBL   IJSYSIN,'POWER360.STARTUP.JCL',99/365,SD
// EXTENT SYSRDR,SPOOL1
// OPTION USRLABEL
/&