// JOB POWER03   LINK POWER
// DLBL IJSYSRL,'POWER.PRIVATE.RELO',99/365,SD
// EXTENT SYSRLB,SPOOL1
// DLBL IJSYSSL,'POWER.PRIVATE.SOURCE',99/365,SD
// EXTENT SYSSLB,SPOOL1
// ASSGN SYSRLB,X'191'
// ASSGN SYSSLB,X'191'
// OPTION CATAL 
   INCLUDE POWEROBJ
// EXEC LNKEDT
/*
/&
