set console -n -q log=console.txt 
set debug -n -q debug.txt

; Motorola Exorciser 

set cpu hex
set cpu noitrap
set cpu nomtrap
set cpu nodebug

set mp-b2 64k
set mp-b2 iobase=fcf0

load Rom/exbug11.bin f000

set mp-b2 rombase=e800

; set Exorciser config to 8N1, RTS=1 (-> value $51 to be written to ACIA control reg)
; on real hw this is done by is set switches ob the back of exorciser
; when done, CPU gets this setting by reading address $fcfd (SBITC in EXBUG source)
set mp-b2 sbitc=51

; set CPU reset vector
dep fffe f0
dep ffff 00

reset 

; uncomment for symbolic debugging
; load Rom/EXBUG11.LST
; load Build/ASMB10_BASE.LST
; load Build/ASMB10_EXBUG.LST
; set cpu debug=symb;inst
; set mp-s debug=all

; Motorola Assembler 1.0
; This is the oldest Motorola 6800 Assembler known to exists
; it is a resident (not co-resident) native assembler from 1975

; boot Monitor 

go until "EXBUG"

; load base program
att ptr Build/ASMB10_BASE.S19
send "LOAD"
go until "SGL/CONT"
send "S"
go until "EXBUG 1.1"
det ptr

; load I/O routines for Motorola Exorciser (sits at 0100-0300) 
att ptr Build/ASMB10_EXBUG.S19
send "LOAD"
go until "SGL/CONT"
send "S"
go until "EXBUG 1.1"
det ptr

; set paper tape punch to no echo to SimH console punched chars
set ptp noecho 

; set here the paper tape source file to assemble
; param1: %1 = source file. If not present, use sample program
; param2: %2 = object file. If not present, use source program with .S19 extension
; param3: %3 = if present, is object file start address, to run the assembled prog

if "%1"!="" goto Ok1

; no params, use sample prog (starts at $0200)
set env SourceFile=Source/ASM_Sample.ASM
set env    ObjFile=Work/ASM_Sample.S19
set env  StartAddr=0200
goto asmb

:Ok1
if "%2"!="" goto Ok2

; only source prog param. 
; Generate Object file as source file with .S19 extension, but no start addr
set env SourceFile=%1
set env    ObjFile=%~pn1.S19
set env  StartAddr=
goto asmb

:Ok2
; both source and object prog param. Set both, and eventually the start addr
set env SourceFile=%1
set env    ObjFile=%2
set env  StartAddr=%3

:asmb
; attach paper tape source file for pass 1
att -q ptr %SourceFile%

; start Motorola Assembler 1.0
send "MAID"
go until "*"
send "0400;G"

; run until control char options message appears
go until "S - PASS 1"

; proceed with pass 1
send "1"
; run until control char options message appears again
; (so pass 1 has finished)
go until "S - PASS 1"

det ptr

; attach again paper tape source file from the beginning to run pass 2
; This generates assembly listing and generates (punches) object file
; so we must attach a tape to be punched

att -q ptr %SourceFile%

; set paper tape punch to no echo to SimH console punched chars
set ptp noecho 

; attach paper tape for object tape. 
att -q -n ptp %ObjFile%

; proceed with pass 2
send "2"
; run until control char options message appears again
; (so pass 2 has finished)
go until "S - PASS 1"

det ptr
det ptp

; exit from assembler and return to monitor
send "X"
go until "EXBUG"

; if no start address defined, just quit
if "%StartAddr%"=="" goto end

; now load object file
att -q ptr %ObjFile%

send "LOAD"
go until "SGL/CONT"
send "S"
go until "EXBUG"
det ptr

; There is a start address defined
; now run object file 

send "MAID"
go until "*"
send "%StartAddr%;G"

go until "EXBUG"

goto end	

:end
